apiVersion: v1
kind: Service
metadata:
  name: Project_Name
  namespace: NS_NAME
spec:
  selector:
    app: Project_Name
  ports:
    - port: Port_name
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  name: Project_Name-ingress
  namespace: NS_NAME
spec:
  rules:
    - host: NS_NAME.example.com
      http:
        paths:
          - backend:
              serviceName: Project_Name
              servicePort: Port_name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Project_Name
  namespace: NS_NAME
  labels:
    app: Project_Name
spec:
  selector:
    matchLabels:
      app: Project_Name
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: Project_Name
    spec:
      containers:
        - image: docker/NS_NAME/Project_Name:latest
          name: Project_Name
          ports:
            - containerPort: Port_name
              name: Project_Name

