apiVersion: v1
kind: Service
metadata:
  name: Project_Name
  namespace: NS_NAME
spec:
  selector:
    app: Project_Name
  ports:
    - port: Port_name
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
  name: Project_Name-ingress
  namespace: NS_NAME
spec:
  rules:
    - host: Project_Name.example.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: Project_Name
                port:
                  number: Port_name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Project_Name
  namespace: NS_NAME
  labels:
    app: Project_Name
spec:
  selector:
    matchLabels:
      app: Project_Name
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: Project_Name
    spec:
      containers:
        - image: docker/NS_NAME/Project_Name:latest
          name: Project_Name
          ports:
            - containerPort: Port_name
              name: Project_Name
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false

